name: Daily Weather

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  fetch-weather:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Fetch weather
        run: python weather.py
      - name: Commit results
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add weather.json
          git commit -m "Update weather" || echo "No changes to commit"
          git push
