name: Daily Weather

permissions:
  contents: write

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  fetch-weather:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Fetch weather
        run: python weather.py

      - name: Commit results
        run: |
          git config user.name "gr39my"
          git config user.email "68382023+gr39my@users.noreply.github.com"
          echo "Updated at $(date)" >> timestamp.txt
          git add .
          git commit -m "Update weather: $(date)" || echo "No changes to commit"
          git push

